package com.alexeyosadchy.android.converter.Models;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.alexeyosadchy.android.converter.Models.Currency;

import com.alexeyosadchy.android.converter.Models.CurrencyDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig currencyDaoConfig;

    private final CurrencyDao currencyDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        currencyDaoConfig = daoConfigMap.get(CurrencyDao.class).clone();
        currencyDaoConfig.initIdentityScope(type);

        currencyDao = new CurrencyDao(currencyDaoConfig, this);

        registerDao(Currency.class, currencyDao);
    }
    
    public void clear() {
        currencyDaoConfig.clearIdentityScope();
    }

    public CurrencyDao getCurrencyDao() {
        return currencyDao;
    }

}
